name: Publish notes

on:
  push:
    branches:
      - main

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            
            - name: Create Blog from Markdown Files
              uses: nilbuild/github-pages-blog-action@v0.0.10